import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/context/auth-context/index.js";
import AdminProvider from "@/context/admin-context"
import { StudentProvider } from "@/context/student-context";
import { ToastContainer, Zoom } from "react-toastify";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Learning Management System",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <AuthProvider>
            <AdminProvider>
              <StudentProvider>
                  {children}
              </StudentProvider>        
            </AdminProvider>
          </AuthProvider>

           <ToastContainer pauseOnHover position="top-right" autoClose={3000} hideProgressBar={false} newestOnTop={true} closeOnClick pauseOnFocusLoss transition={Zoom} theme="colored"/>
      </body>
    </html>
  );
}
